# Generated by Django 4.2.10 on 2024-02-25 14:42

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.PositiveSmallIntegerField()),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#287d38', 'green'), ('#305bd1', 'blue'), ('#631e9c', 'purple'), ('#ed9f32', 'orange')])),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_health', models.IntegerField(default=100)),
                ('base_max_health', models.IntegerField(default=100)),
                ('base_mana', models.IntegerField(default=100)),
                ('base_max_mana', models.IntegerField(default=100)),
                ('base_strength', models.IntegerField(default=10)),
                ('base_intelligence', models.IntegerField(default=10)),
                ('base_agility', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='rpg.characterclass')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='rpg.guild')),
                ('quests', models.ManyToManyField(related_name='characters', to='rpg.quest')),
                ('statistics', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='character', to='rpg.statistics')),
            ],
        ),
    ]
