# Generated by Django 4.2.10 on 2024-02-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_item_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='experience_level_up',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
