# Generated by Django 3.2 on 2024-02-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_character_experience_character_experience_level_up_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='experience_level_up',
            new_name='max_experience',
        ),
    ]
