# Generated by Django 3.2 on 2024-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_rename_experience_level_up_character_max_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='sustained_damage',
            field=models.IntegerField(default=0),
        ),
    ]
