# Generated by Django 3.2 on 2024-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_statistics_sustained_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='depleted_mana',
            field=models.IntegerField(default=0),
        ),
    ]
